name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ec2-user@3.133.149.131:/home/ec2-user/app/

      - name: SSH into EC2 and run Docker
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.133.149.131 << 'EOF'
            cd /home/ec2-user/app
            docker stop react-cd || true
            docker rm react-cd || true
            docker build -t react-cd-app .
            docker run -d -p 80:80 --name react-cd react-cd-app
          EOF
